# Use docker/docker as user/password credentials

services:
  postgresqldb:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
    environment:
      ADMINER_DESIGN: pepa-linha
    depends_on:
      - postgresqldb
