# Use docker/docker as user/password credentials

services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: docker
      MONGO_INITDB_ROOT_PASSWORD: docker
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
			- 8092:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_ADMINUSERNAME: docker
      ME_CONFIG_MONGODB_ADMINPASSWORD: docker
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
