# Use sa/docker as user/password credentials

services:
  mssqldb:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      SA_PASSWORD: f2c8d8ca4bcbca5fa79afad919238ffbc61de562
      ACCEPT_EULA: 1
    volumes:
      - ./data:/var/opt/mssql/data
    ports:
      - 1433:1433

  adminer:
    image: adminer
    ports:
      - 8090:8080
    environment:
      ADMINER_DESIGN: pepa-linha
    depends_on:
      - mssqldb
