# Use root/docker as user/password credentials

services:
  mysqldb:
    image: mysql
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: docker
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8091:8080
    environment:
      ADMINER_DESIGN: pepa-linha
    depends_on:
      - mysqldb
